package com.cn.domain;

import java.io.Serializable;

/**
 * Model class of 城市采集内容.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CityDetailItem implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 明细ID. */
	private String itemId;

	/** 采集项ID. */
	private String cdid;

	/** 城市ID. */
	private String regionId;

	/** 采集内容. */
	private String detail;

	/** CREATE_TIME. */
	private String createTime;

	/** 是否为图像地址. */
	private Integer isImg;

	/**
	 * Constructor.
	 */
	public CityDetailItem() {
	}

	/**
	 * Set the 明细ID.
	 * 
	 * @param itemId
	 *            明细ID
	 */
	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	/**
	 * Get the 明细ID.
	 * 
	 * @return 明细ID
	 */
	public String getItemId() {
		return this.itemId;
	}

	/**
	 * Set the 采集项ID.
	 * 
	 * @param cdid
	 *            采集项ID
	 */
	public void setCdid(String cdid) {
		this.cdid = cdid;
	}

	/**
	 * Get the 采集项ID.
	 * 
	 * @return 采集项ID
	 */
	public String getCdid() {
		return this.cdid;
	}

	/**
	 * Set the 城市ID.
	 * 
	 * @param regionId
	 *            城市ID
	 */
	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	/**
	 * Get the 城市ID.
	 * 
	 * @return 城市ID
	 */
	public String getRegionId() {
		return this.regionId;
	}

	/**
	 * Set the 采集内容.
	 * 
	 * @param detail
	 *            采集内容
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * Get the 采集内容.
	 * 
	 * @return 采集内容
	 */
	public String getDetail() {
		return this.detail;
	}

	/**
	 * Set the CREATE_TIME.
	 * 
	 * @param createTime
	 *            CREATE_TIME
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the CREATE_TIME.
	 * 
	 * @return CREATE_TIME
	 */
	public String getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 是否为图像地址.
	 * 
	 * @param isImg
	 *            是否为图像地址
	 */
	public void setIsImg(Integer isImg) {
		this.isImg = isImg;
	}

	/**
	 * Get the 是否为图像地址.
	 * 
	 * @return 是否为图像地址
	 */
	public Integer getIsImg() {
		return this.isImg;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CityDetailItem other = (CityDetailItem) obj;
		if (itemId == null) {
			if (other.itemId != null) {
				return false;
			}
		} else if (!itemId.equals(other.itemId)) {
			return false;
		}
		return true;
	}

}
